Updated My Portfolio with responsive desktop version
V-Blaze/My-Portfolio pull request #4
Opened 2022-09-28 15:20 UTC by V-Blaze

I updated the My portfolio webpage and added responsive styling for desktops using media queries. Below are the major changes:

- Removed the mobile menu and added a desktop menu for bigger screen devices
- Added responsive Styling to the header section for a better desktop experience.
- Added a Different layout to the work section for the desktop version
- Made the about-me and contact section responsive to a bigger screen.

2022-09-28 17:04 UTC, jerryowusu requested changes
Hi @V-Blaze 

Good job so far!
Your project is looking fantastic :star_struck: 

However, I've found some room for improvement that can help you accomplish a more readable/clean code and make your project look professional :sunglasses:

![so close](https://user-images.githubusercontent.com/65233860/192844509-23b724b1-5eb2-4922-ae3e-a3a110d2930d.gif)

## Highlights
:heavy_check_mark: Followed GitHub Flow
:heavy_check_mark: Descriptive PR Summary
:heavy_check_mark: All Linters are passing

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-28 17:04 UTC, jerryowusu commented on index.html
> +                </h1>
It looks almost all your `p` tags and `hx` tags is centred but it is supposed to be aligned to the left. Kindly go thru your project and correct this. Please note that almost all of the paragraphs (`p` tags) and headers (`hx` tags) in the design is supposed to be left aligned. Below are just a few pictorial examples:




Your design             |  Figma design
:-------------------------:|:-------------------------:
![Screenshot from 2022-09-28 16-25-09](https://user-images.githubusercontent.com/65233860/192834246-c556d9e6-1c1d-4856-bb7f-5ff41fe80f79.png)  |  ![Screenshot from 2022-09-28 16-20-56](https://user-images.githubusercontent.com/65233860/192834277-ac98f577-f430-40a5-825f-a327724f7fa2.png)



Your design             |  Figma design
:-------------------------:|:-------------------------:
![Screenshot from 2022-09-28 16-18-11](https://user-images.githubusercontent.com/65233860/192839723-9b626cf9-8a9e-4bd8-bc3c-b44a723dc7de.png)  |  ![Screenshot from 2022-09-28 16-21-12](https://user-images.githubusercontent.com/65233860/192839780-c01226c4-aefa-44f8-b652-6cb4d336c6b9.png)



Your design             |  Figma design
:-------------------------:|:-------------------------:
![Screenshot from 2022-09-28 16-19-08](https://user-images.githubusercontent.com/65233860/192840950-9c640dac-53c4-456f-8946-d62e9cfd959e.png)  |  ![Screenshot from 2022-09-28 16-21-26](https://user-images.githubusercontent.com/65233860/192841045-753b6830-dacd-4123-8a0a-dc2a508368b7.png)

2022-09-28 17:04 UTC, jerryowusu commented on style.css
> +  }
At certain breakpoints of the media screen, the design does not look like the figma design with lots of variations and distortions whiles it looks perfectly fine at other breakpoints. You can consider adding other media query breakpoints and flexbox to make your app more responsive. Check the images below at to see some of the distortions at breakpoint 770px to 990px

Your design             |  Figma design
:-------------------------:|:-------------------------:   
![Screenshot from 2022-09-28 16-49-33](https://user-images.githubusercontent.com/65233860/192843544-f4e2daef-ba7c-42d2-8d3c-a764125cd673.png)  |  ![Screenshot from 2022-09-28 16-49-57](https://user-images.githubusercontent.com/65233860/192843434-656f9922-26c8-4b9f-ae78-862aafd41515.png)


Your design             |  Figma design
:-------------------------:|:-------------------------:
![Screenshot from 2022-09-28 16-49-23](https://user-images.githubusercontent.com/65233860/192843635-01dc21e9-1110-4839-967d-50f0355e187d.png)  |  ![Screenshot from 2022-09-28 16-50-27](https://user-images.githubusercontent.com/65233860/192843662-269d1fa4-2068-4ef5-84df-a5c9c26e2b58.png)

2022-09-29 12:52 UTC, V-Blaze commented
Below are the major corrections made to the code as requested by the reviewer:

- [ ] Aligned the p tags and hx tags to the left in line with the Figma file
- [ ] Added media queries at min-width: 768px and 992px for better responsiveness on different screen sizes.

2022-09-29 12:58 UTC, Gopxfs commented
# 🟢 STATUS: APPROVED 🟢

## Hello @V-Blaze 👋,

Your project is complete! You followed all the requirements, feel free to merge it! 😄
Congratulations! 🎉 

<img src="https://media.giphy.com/media/cXblnKXr2BQOaYnTni/giphy.gif">

## Highlights
✔️ Linters are passing successfully.
✔️ Implemented all the changes requested by the previous reviewer. Well done!

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-09-29 13:12 UTC, merged